// Mock data for development when database is unavailable
import type { HazardAlert } from "./types"

export const mockAlerts: HazardAlert[] = [
  {
    id: 1,
    external_id: "GDACS-TC-2024001",
    source: "GDACS",
    hazard_type: "CYCLONE",
    severity: "RED",
    title: "Tropical Cyclone Belal",
    description: "Tropical Cyclone Belal affecting Mauritius and Reunion Islands with heavy rainfall and strong winds.",
    country: "Mauritius",
    region: "Indian Ocean",
    latitude: -20.2,
    longitude: 57.5,
    event_start: "2026-01-15T00:00:00Z",
    event_end: null,
    is_active: true,
    population_affected: 150000,
    source_url: "https://www.gdacs.org/report.aspx?eventid=1000001",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-01-15T00:00:00Z",
  },
  {
    id: 2,
    external_id: "GDACS-FL-2024002",
    source: "GDACS",
    hazard_type: "FLOOD",
    severity: "ORANGE",
    title: "Nigeria Floods - Niger Delta",
    description: "Severe flooding in the Niger Delta region affecting multiple states.",
    country: "Nigeria",
    region: "Niger Delta",
    latitude: 5.0,
    longitude: 6.3,
    event_start: "2026-01-10T00:00:00Z",
    event_end: null,
    is_active: true,
    population_affected: 50000,
    source_url: "https://www.gdacs.org/report.aspx?eventid=1000002",
    created_at: "2026-01-10T00:00:00Z",
    updated_at: "2026-01-10T00:00:00Z",
  },
  {
    id: 3,
    external_id: "NASA-12345",
    source: "NASA_EONET",
    hazard_type: "WILDFIRE",
    severity: "YELLOW",
    title: "Forest Fire - Mount Kenya Region",
    description: "Wildfire burning in forest areas near Mount Kenya.",
    country: "Kenya",
    region: "Mount Kenya",
    latitude: -0.15,
    longitude: 37.3,
    event_start: "2026-01-12T00:00:00Z",
    event_end: null,
    is_active: true,
    population_affected: null,
    source_url: "https://eonet.gsfc.nasa.gov/api/v3/events/12345",
    created_at: "2026-01-12T00:00:00Z",
    updated_at: "2026-01-12T00:00:00Z",
  },
  {
    id: 4,
    external_id: "GDACS-DR-2024003",
    source: "GDACS",
    hazard_type: "DROUGHT",
    severity: "ORANGE",
    title: "Eastern Africa Drought",
    description: "Prolonged drought affecting parts of Ethiopia, Kenya, and Somalia.",
    country: "Ethiopia",
    region: "Eastern Highlands",
    latitude: 9.0,
    longitude: 40.0,
    event_start: "2025-11-01T00:00:00Z",
    event_end: null,
    is_active: true,
    population_affected: 2000000,
    source_url: "https://www.gdacs.org/report.aspx?eventid=1000003",
    created_at: "2025-11-01T00:00:00Z",
    updated_at: "2025-11-01T00:00:00Z",
  },
  {
    id: 5,
    external_id: "RELIEFWEB-98765",
    source: "RELIEFWEB",
    hazard_type: "FLOOD",
    severity: "RED",
    title: "Libya Flash Floods - Derna",
    description: "Catastrophic flooding in Derna after Storm Daniel caused dam collapses.",
    country: "Libya",
    region: "Derna",
    latitude: 32.75,
    longitude: 22.65,
    event_start: "2025-09-10T00:00:00Z",
    event_end: null,
    is_active: true,
    population_affected: 100000,
    source_url: "https://reliefweb.int/disaster/fl-2023-000165-lby",
    created_at: "2025-09-10T00:00:00Z",
    updated_at: "2025-09-10T00:00:00Z",
  },
]

export const mockPipelineStatus = {
  pipeline: [
    {
      source: "GDACS",
      status: "SUCCESS",
      records_fetched: 45,
      records_inserted: 2,
      records_updated: 3,
      error_message: null,
      response_time_ms: 2345,
      started_at: new Date(Date.now() - 300000).toISOString(),
      completed_at: new Date(Date.now() - 297000).toISOString(),
    },
    {
      source: "NASA_EONET",
      status: "SUCCESS",
      records_fetched: 120,
      records_inserted: 1,
      records_updated: 0,
      error_message: null,
      response_time_ms: 1890,
      started_at: new Date(Date.now() - 600000).toISOString(),
      completed_at: new Date(Date.now() - 598000).toISOString(),
    },
    {
      source: "RELIEFWEB",
      status: "SUCCESS",
      records_fetched: 25,
      records_inserted: 0,
      records_updated: 1,
      error_message: null,
      response_time_ms: 3100,
      started_at: new Date(Date.now() - 900000).toISOString(),
      completed_at: new Date(Date.now() - 897000).toISOString(),
    },
  ],
  summary: {
    total_active_alerts: mockAlerts.length,
    by_severity: [
      { severity: "RED", count: 2 },
      { severity: "ORANGE", count: 2 },
      { severity: "YELLOW", count: 1 },
    ],
    by_hazard_type: [
      { hazard_type: "FLOOD", count: 2 },
      { hazard_type: "CYCLONE", count: 1 },
      { hazard_type: "WILDFIRE", count: 1 },
      { hazard_type: "DROUGHT", count: 1 },
    ],
  },
  timestamp: new Date().toISOString(),
}

export const mockReports = [
  {
    id: 1,
    report_type: "Eyewitness",
    hazard_type: "FLOOD",
    severity_estimate: "ORANGE",
    title: "Flooding in Lagos Suburbs",
    description: "Significant flooding observed in residential areas after heavy overnight rains.",
    reporter_name: "John Doe",
    reporter_contact: "john@example.com",
    reporter_organization: "Community Watch",
    country: "Nigeria",
    region: "Lagos State",
    locality: "Ikeja",
    lat: 6.6,
    lon: 3.35,
    people_affected_estimate: 500,
    infrastructure_damage: "Roads blocked, some homes flooded",
    immediate_needs: "Clean water, temporary shelter",
    verification_status: "UNVERIFIED",
    is_active: true,
    reported_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 2,
    report_type: "Damage Assessment",
    hazard_type: "CYCLONE",
    severity_estimate: "RED",
    title: "Cyclone damage in coastal areas",
    description: "Multiple structures damaged, power lines down.",
    reporter_name: "Jane Smith",
    reporter_contact: "jane@redcross.org",
    reporter_organization: "Red Cross",
    country: "Mozambique",
    region: "Sofala",
    locality: "Beira",
    lat: -19.8,
    lon: 34.9,
    people_affected_estimate: 2000,
    infrastructure_damage: "Hospitals, schools, roads damaged",
    immediate_needs: "Medical supplies, food, water",
    verification_status: "VERIFIED",
    is_active: true,
    reported_at: new Date(Date.now() - 172800000).toISOString(),
  },
]
